### ISSUE TITLE
NameError: global name 'OSMesaCreateContext' is not defined

### ISSUE THREAD

**Issue by fariza** [ramezquitao/pyoptools#12]
Intentando correr los ejemplos mas basicos encuentro este error en Python2.7

```
from pyoptools.all import *
P1=Plane(shape=Circular(radius=(25)))
plot3D(P1,center=(0,0,0),size=(60,60),rot=[(0,0,0)],scale=6)

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-3-9deb8f035d24> in <module>()
----> 1 plot3D(P1,center=(0,0,0),size=(60,60),rot=[(0,0,0)],scale=6)

/home/fariza/workspace/pyoptools/pyoptools/gui/ipynbplotutils.pyc in plot3D(os, center, size, rot, scale)
    175     #bottom=center[1]-size[1]/2
    176 
--> 177     ctx = OSMesaCreateContext(GL_RGBA, None)
    178 
    179     width,height=int(size[0]*scale),int(size[1]*scale)

NameError: global name 'OSMesaCreateContext' is not defined
```

**Comment by ramezquitao** [comment]
Hola Federico

Una pregunta, que versión del pyopengl estas usando? Tienes instalado el
OSMesa?

Ricardo

Ricardo Amézquita Orozco

ramezquitao@cihologramas.com
ramezquitao@unal.edu.co
ramezquitao@gmail.com

2015-06-10 17:31 GMT-05:00 Federico Ariza <notifications@github.com>:

**Comment by fariza** [comment]
PyOpenGL-3.1.0
Tengo instalado el `libosmesa6` del ubuntu

Una cosa que puede ser importante...
```
In [1]: from pyoptools.all import *
Loading component library Edmund  from files  ['pyoptools/raytrace/library/Edmund/SphOptics1.cmp', 'pyoptools/raytrace/library/Edmund/SphOptics.cmp']
need OSMesa installed, and the following environment variable
export PYOPENGL_PLATFORM=osmesa
```

**Comment by ijpulidos** [comment]
¿Cómo está lanzando/ejecutando pyoptools? 

Si está ejecutando ipython "puro" y desde ahí importando pyoptools es necesario definir esa variable de entorno, es decir, ejecutar el comando "export PYOPENGL_PLATFORM=osmesa" en la terminal. Puede agregar esa línea a su archivo .bashrc para que se ejecute automáticamente apenas inicie sesión.

Otra forma de ejecutar pyoptools es con el comando "ipyoptools" que no necesita configurar esta variable de entorno.

**Comment by fariza** [comment]
Perfecto, yo pense que el mensaje estaba relacionado con la carga de los archivos de Edmund.
Gracias
