### ISSUE TITLE
travis

### ISSUE THREAD

**Issue by fariza** [ramezquitao/pyoptools#16]
@ramezquitao puse el archivo de travis y esta corriendo un test muy basico `pep2 setup.py` solo para verificar que el `python setup install` funciona en python 2.7 y 3.4.
Le toca a usted activar el travis para pyoptools.

Lo que pensaba era crear un modulo de tests, donde se vayan creando los tests de los modulos antes de hacerles ninguna modificacion, asi podemos verificar que no dannamos nada al tocarlos.
Que opina?

**Comment by fariza** [comment]
De paso, yo me voy de vacaciones esta semana, asi que no estare por aqui. Solo para que le de envidia
PUNTA CANA papa!!!

**Comment by ramezquitao** [comment]
@fariza como le fue de paseo? 

No le entiendo cuando me dice que tengo que activar el travis para pyoptools

**Comment by fariza** [comment]
Hola Ricardo me fue muy bien afortunadamente.

Con respecto a lo de Travis (esta es mi primera vez) el dueño del repositorio tiene que activar la máquina virtual de Travis para que los tests sean ejecutados automáticamente con los push

**Comment by ramezquitao** [comment]
Listo Federico. Creo que ya quedo activado. Me cuenta como le va con eso

**Comment by fariza** [comment]
Tengo que ponerme a hacer el directorio de tests y empezar por hacer el test del pep8 global.
