### ISSUE TITLE
crear releases

### ISSUE THREAD

**Issue by fariza** [ramezquitao/pyoptools#19]
@ramezquitao seria bueno crear releases para marcar puntos en la historia considerados "estables", esto en git se hace con tags

Asi podemos hacer cambios en el master que no afectan lo que se considera estable sin tener que tener un branch especial para eso.

**Comment by ramezquitao** [comment]
Me parece bien. Lo que nos tocaria es definir es que deberían contener los diferentes releases. En particular verificar si en este momento estamos listos para hacer un release, o que nos esta haciendo falta.

**Comment by fariza** [comment]
En este momento el codigo es "funcional", podria ser el release 0.1 o 1.0
Es que hacer cualquier cambio de arquitectura puede ser **destructivo** en este momento, entonces para preservar un estado estable e instalable necesitamos un release.

**Comment by ramezquitao** [comment]
Sugiero una cosa.

Hagamosle una buena revisión al código para eliminar algo de basura que
hay. Y a finales de la semana entrante declaremos el release, sin importar
que hayamos eliminado toda la basura o no.




Ricardo Amézquita Orozco
Doctor en Ciencias - Física
Director de Investigación y Desarrollo

CI Hologramas - Combustión Ingenieros S.A.S.
Cll 25B # 85B - 76, Bogotá / Colombia
Tel: 57-1-2635232
Fax: 57-1-4296516
http://www.cihologramas.com

El 11 de septiembre de 2015, 10:29, Federico Ariza <notifications@github.com

**Comment by fariza** [comment]
Hmmm, ok, pero como sabemos que es basura? sin tests, toca solo la persona que conoce el codigo de memoria... usted :smile:

**Comment by ramezquitao** [comment]
Por eso puse el limite de la semana entrante, por que si no no lo hacemos
nunca.

Voy a borrar algunas cosas que se que no sirven, y respecto a unas en las
que tengo duda, pondré comentarios acá para que los discutamos.

De todas maneras, pase lo que pase la semana entrante creamos el release.
Si luego hay basura que borrar, lo hacemos como una revisión al release.

Le parece? O mejor hacemos el release ya, y la borrada de basura la hacemos
como revisiones al release?


Ricardo Amézquita Orozco
Doctor en Ciencias - Física
Director de Investigación y Desarrollo

CI Hologramas - Combustión Ingenieros S.A.S.
Cll 25B # 85B - 76, Bogotá / Colombia
Tel: 57-1-2635232
Fax: 57-1-4296516
http://www.cihologramas.com

El 11 de septiembre de 2015, 10:41, Federico Ariza <notifications@github.com

**Comment by fariza** [comment]
La borrada de basura siempre tiene riesgos....
Yo preferiria un release y ya, es funcional, no bonito pero funcional.
La borrada de basura la hacemos ya dentro del desarrollo en el master, a ese relase solo le hacemos bugfixes y no mas.

**Comment by ramezquitao** [comment]
Listo

Hagamos ya el release 0.1


Ricardo Amézquita Orozco
Doctor en Ciencias - Física
Director de Investigación y Desarrollo

CI Hologramas - Combustión Ingenieros S.A.S.
Cll 25B # 85B - 76, Bogotá / Colombia
Tel: 57-1-2635232
Fax: 57-1-4296516
http://www.cihologramas.com

El 11 de septiembre de 2015, 11:00, Federico Ariza <notifications@github.com

**Comment by ramezquitao** [comment]
Listo, tag v0.1 adicionado
