### ISSUE TITLE
instalable desde pipy

### ISSUE THREAD

**Issue by fariza** [ramezquitao/pyoptools#21]
Como se pueden simplificar las dependencias para que sea instalable desde pipy?

**Comment by ramezquitao** [comment]
Inicialmente la idea era incluir un programa con interfaz gráfica que
permitiera visualizar las simulaciones. Aunque a esto no se le ha seguido
trabajando y yo hace rato no lo uso, existe un código que permite hacer una
previsualización de las simulaciones usando opengl y wx. Este código se
podría eliminar para quitar las dependencias de wx. Este widget es el que
se muestra en el video https://www.youtube.com/watch?v=DB8sfm7pVPI

Al hacer esto las únicas dependencias que quedan son:
numpy
scipy (no estoy seguro si es completamente necesario, de pronto no)
matplotlib (para hacer los spot diagrams)
pyopengl, con soporte para osmesa (para hacer los renderings que se
visualizan en los notebooks de ipython). Esto lo podemos quitar si se hacen
visualizaciones usando webgl
ipython (para poder hacer las visualizaciones en los notebooks)
cython y sus dependencias (para poder compilar)

y creo que nada mas.

Contesta esto la pregunta?



Ricardo Amézquita Orozco
Doctor en Ciencias - Física
Director de Investigación y Desarrollo

CI Hologramas - Combustión Ingenieros S.A.S.
Cll 25B # 85B - 76, Bogotá / Colombia
Tel: 57-1-2635232
Fax: 57-1-4296516
http://www.cihologramas.com

2015-09-11 15:35 GMT-05:00 Federico Ariza <notifications@github.com>:

**Comment by fariza** [comment]
El programa con wx me parece que vale la pena moverlo a otro repo.
Pero por lo que veo esta muy metido dentro del mismo codigo.

Ipython lo podemos dejar como dependencia, es instalable desde pypi

**Comment by ramezquitao** [comment]
Listo, dejeme y durante el fin de semana yo hago eso y le aviso.




Ricardo Amézquita Orozco
Doctor en Ciencias - Física
Director de Investigación y Desarrollo

CI Hologramas - Combustión Ingenieros S.A.S.
Cll 25B # 85B - 76, Bogotá / Colombia
Tel: 57-1-2635232
Fax: 57-1-4296516
http://www.cihologramas.com

El 11 de septiembre de 2015, 16:52, Federico Ariza <notifications@github.com

**Comment by ramezquitao** [comment]
Listo Federico, los cambios quedaron hechos. En este momento pyoptools
compila, y los ejemplos corren. Lo probe con python 2 no con python 3.

Ricardo


Ricardo Amézquita Orozco
Doctor en Ciencias - Física
Director de Investigación y Desarrollo

CI Hologramas - Combustión Ingenieros S.A.S.
Cll 25B # 85B - 76, Bogotá / Colombia
Tel: 57-1-2635232
Fax: 57-1-4296516
http://www.cihologramas.com
