### ISSUE TITLE
unused branches

### ISSUE THREAD

**Issue by fariza** [ramezquitao/pyoptools#22]
Podemos borrar stable and wiki branches?

**Comment by ramezquitao** [comment]
Yo diría que si.


Ricardo Amézquita Orozco
Doctor en Ciencias - Física
Director de Investigación y Desarrollo

CI Hologramas - Combustión Ingenieros S.A.S.
Cll 25B # 85B - 76, Bogotá / Colombia
Tel: 57-1-2635232
Fax: 57-1-4296516
http://www.cihologramas.com

2015-09-11 15:37 GMT-05:00 Federico Ariza <notifications@github.com>:

**Comment by fariza** [comment]
Done
