### ISSUE TITLE
reemplazar scipy.weave

### ISSUE THREAD

**Issue by fariza** [ramezquitao/pyoptools#26]
`scipy.weave` es obsoleto y no esta dentro del paquete de scipy de python3 instalado desde pip.
Hay que eliminar esa dependencia.
Desafortunadamente mi conocimiento de cpython es practicamente nulo, asi que  no se que hay que hacer ups :cry:

**Comment by ramezquitao** [comment]
El weave no se debe estar usando. Ese import se debe poder eliminar

**Comment by fariza** [comment]
Yo revise y si esta siendo usado

**Comment by fariza** [comment]
https://github.com/ramezquitao/pyoptools/search?utf8=%E2%9C%93&q=weave
* `pyoptools/raytrace/surface/spherical.pyx`
* `pyoptools/misc/lsq/lsq.pyx`
