### ISSUE TITLE
tutorial: glPlotFrame

### ISSUE THREAD

**Issue by ColinBrosseau** [ramezquitao/pyoptools#38]
Hi,

I installed it on ArchLinux. I'm following the tutorial. I'm stuck at line:
glPlotFrame(S)
This is not defined anywhere. Where does it come from?

**Comment by fariza** [comment]
Sorry for the delay, the documentation needs some work.

Try running some basic examples in basic_course

**Comment by fariza** [comment]
I tested the the basic course notebooks in python3 and most of them work
`https://github.com/ramezquitao/pyoptools/tree/master/examples/basic_course`
How did you install? from source (github?)

If so, don't forget you need to install in python `pyopengl` and for your distribution `libosmesa6` and `libosmesa6-dev`

**Comment by ramezquitao** [comment]
As the documentation needs some work, a Virtualbox image (debian8) with pyoptools installed and working is provided at:

https://drive.google.com/open?id=0B6vN2VIpMQ48THUwX1NJSjM0cEE

    user name: usuario
    password usuario
